#ifndef LANG_JA_H
#define LANG_JA_H

// efont 日本語フォントを使用
#include <lgfx/Fonts/efont/lgfx_efont_ja.h>
#define USE_EFONT 1

#define L_WAITING    "待機中..."
#define L_DETECTED   "検知!"
#define L_NO_MOTION  "未検知"
#define L_STATUS     "状態:"
#define L_SENSOR     "センサー:"
#define L_SETTINGS   "設定"
#define L_LOGS       "ログ"
#define L_REFRESH    "更新"
#define L_BACK       "戻る"
#define L_PREV       "前"
#define L_NEXT       "次"
#define L_SELECT     "決定"
#define L_DAILY      "日別"
#define L_DAILY_SUMMARY "日別サマリー"
#define L_NO_DATA    "データなし"
#define L_NO_LOGS    "ログがありません"
#define L_TIMES      "回"
#define L_AVG        "平均"
#define L_MAX        "最大"
#define L_MIN        "最小"
#define L_SEARCHING  "Bridgeを探索中..."
#define L_FOUND      "発見:"
#define L_SEARCH_FAIL "自動探索に失敗しました"
#define L_PRESS_BRIDGE "Hue Bridgeのボタンを"
#define L_PRESS_BRIDGE2 "押してください"
#define L_RETRY_AUTO "3秒ごとに自動リトライします"
#define L_RETRYING   "リトライ中..."
#define L_API_OK     "APIキーを取得しました!"
#define L_API_TIMEOUT "APIキー取得がタイムアウトしました"
#define L_LOADING    "センサー読込中..."
#define L_SELECT_SENSOR "センサーを選択:"
#define L_SENSOR_FAIL "センサー取得に失敗"
#define L_JSON_ERROR "JSON解析エラー"
#define L_NO_SENSORS "人感センサーが見つかりません"
#define L_SELECTED   "選択:"
#define L_WIFI_FAIL  "WiFi接続に失敗しました"
#define L_SETTINGS_1 "設定 (1/2)"
#define L_SETTINGS_2 "設定 (2/2)"
#define L_WIFI_RESET "WiFi 再設定"
#define L_WIFI_HINT  "(シリアルで再入力)"
#define L_HUE_RESET  "Hue Bridge 再設定"
#define L_HUE_HINT   "(探索→ペアリング→選択)"
#define L_ALARM_TEST "アラーム試聴"
#define L_ALARM_HINT "アラート音を再生します"
#define L_PLAYING    "再生中..."
#define L_DONE       "完了"
#define L_WIFI_CONFIRM "WiFi設定をクリアして"
#define L_WIFI_CONFIRM2 "再起動しますか？"
#define L_HUE_CONFIRM "Hue Bridge設定を"
#define L_HUE_CONFIRM2 "再設定しますか？"
#define L_EXECUTE    "実行"
#define L_CANCEL     "キャンセル"
#define L_RESET_REBOOT "設定リセット & 再起動"
#define L_CLEARED    "設定をリセットしました"
#define L_REBOOTING  "  再起動します..."
#define L_NOT_FOUND  "  見つかりません。再選択..."
#define L_HUE_RECONFIG "Hue Bridge 再設定..."

#endif
