#ifndef LANG_EN_H
#define LANG_EN_H

// English: no efont needed
#define USE_EFONT 0

#define L_WAITING    "Waiting..."
#define L_DETECTED   "Detected!"
#define L_NO_MOTION  "No motion"
#define L_STATUS     "Status:"
#define L_SENSOR     "Sensor:"
#define L_SETTINGS   "Settings"
#define L_LOGS       "Logs"
#define L_REFRESH    "Refresh"
#define L_BACK       "Back"
#define L_PREV       "Prev"
#define L_NEXT       "Next"
#define L_SELECT     "Select"
#define L_DAILY      "Daily"
#define L_DAILY_SUMMARY "Daily Summary"
#define L_NO_DATA    "No data"
#define L_NO_LOGS    "No logs"
#define L_TIMES      "x"
#define L_AVG        "Avg"
#define L_MAX        "Max"
#define L_MIN        "Min"
#define L_SEARCHING  "Searching Bridge..."
#define L_FOUND      "Found:"
#define L_SEARCH_FAIL "Auto-discovery failed"
#define L_PRESS_BRIDGE "Press the button on"
#define L_PRESS_BRIDGE2 "your Hue Bridge"
#define L_RETRY_AUTO "Auto-retry every 3s"
#define L_RETRYING   "Retrying..."
#define L_API_OK     "API Key obtained!"
#define L_API_TIMEOUT "API Key timeout"
#define L_LOADING    "Loading sensors..."
#define L_SELECT_SENSOR "Select Sensor:"
#define L_SENSOR_FAIL "Failed to get sensors"
#define L_JSON_ERROR "JSON parse error"
#define L_NO_SENSORS "No motion sensors found"
#define L_SELECTED   "Selected:"
#define L_WIFI_FAIL  "WiFi connection failed"
#define L_SETTINGS_1 "Settings (1/2)"
#define L_SETTINGS_2 "Settings (2/2)"
#define L_WIFI_RESET "WiFi Reset"
#define L_WIFI_HINT  "(Serial input required)"
#define L_HUE_RESET  "Hue Bridge Reset"
#define L_HUE_HINT   "(Discover > Pair > Select)"
#define L_ALARM_TEST "Alarm Test"
#define L_ALARM_HINT "Play alert sound"
#define L_PLAYING    "Playing..."
#define L_DONE       "Done"
#define L_WIFI_CONFIRM "Clear WiFi settings and"
#define L_WIFI_CONFIRM2 "reboot?"
#define L_HUE_CONFIRM "Reconfigure"
#define L_HUE_CONFIRM2 "Hue Bridge?"
#define L_EXECUTE    "OK"
#define L_CANCEL     "Cancel"
#define L_RESET_REBOOT "Reset & Reboot"
#define L_CLEARED    "Settings cleared"
#define L_REBOOTING  "  Rebooting..."
#define L_NOT_FOUND  "  Not found. Re-select..."
#define L_HUE_RECONFIG "Hue Bridge setup..."

#endif
